name: Deploy Bicep file

on:
  push:
    branches:
      - main
      - bicep

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set debug environment variable
        run: echo "AZURE_ARM_DEPLOY_LOG_LEVEL=debug" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure resource group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
            echo "Azure resource group created"

      - name: Deploy Bicep file
        id: bicep-deploy
        uses: azure/arm-deploy@v1
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS | fromJson | select(.subscriptionId) }}
        with:
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.ResourceGroupName }}
          template: ./Infrastructure/main.bicep
          parameters: ./Infrastructure/main.bicepparam
          deploymentName: sampleDeployment
          deploymentMode: Complete
          additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
          failOnStdErr: false

      - name: Get deployment outputs
        run: |
          echo "Provisioning State: ${{ steps.bicep-deploy.outputs['topicProvisioningState'] }}"
