name: Deploy Bicep file

on:
  push:
    branches:
      - main
      - bicep
      - sample

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set debug environment variable
        run: echo "AZURE_ARM_DEPLOY_LOG_LEVEL=debug" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Extract subscription ID from Azure credentials
        id: extract-subscription-id
        run: echo "AZURE_SUBSCRIPTION_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.subscriptionId')" >> $GITHUB_ENV

      - name: Check if App Service exists
        id: check_app
        run: |
          if az webapp list --resource-group ${{ vars.ResourceGroupName }} --query "[?name=='sample-web-app-nacho']" | grep -q 'sample-web-app-nacho'; then
            echo "exists=true" >> $GITHUB_ENV
            echo "webapp exists"
          else
            echo "exists=false" >> $GITHUB_ENV
            echo "webapp doesnt exists"
          fi

      - name: Deploy Bicep file
        if: env.exists == 'false'
        id: bicep-deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.ResourceGroupName }}
          template: ./Bicep/sample.bicep
          # parameters: ./Bicep/sample.bicepparam
          deploymentName: sampleDeployment
          failOnStdErr: false
