name: Deploy Bicep file

on:
  push:
    branches:
      - main
      - bicep

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      id: bicep-deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: 800eeb5c-ab87-468f-800b-d9ca632b4f73
        resourceGroupName: demo
        template: ./Infrastructure/main.bicep
        parameters: ./Infrastructure/main.bicepparam
        deploymentName: sampleDeployment
        deploymentMode: Complete
        failOnStdErr: false
        bicep_use_binary_from_path: true

    - name: Get deployment outputs
      run: |
        echo "Outputs: ${{ steps.bicep-deploy.outputs['topicEndpoint'] }}"
        echo "Provisioning State: ${{ steps.bicep-deploy.outputs['topicProvisioningState'] }}"